introduction:
  ğŸº: "**é‚¶æŸ’EvATive7**"
  ğŸ’: Enciodes SilverAsh
  âšª: ã€Œ lex parsimoniae ã€
badge:
  I use:
    - - Android
      - Flutter
      - - Vue
        - vuedotjs
      - .NET
      - Spring
      - Nginx
      - TensorFlow
  with:
    - - Python
      - JavaScript
      - TypeScript
      - - C#
        - csharp
      - - C++
        - cplusplus
      - - Java
        - oracle
      - - Dart
        - dart
    - - - Material_Design
        - materialdesign
    - - - Code
        - visualstudiocode
      - - Git
        - git
      - - Firefox
        - firefoxbrowser
  "on":
    - - - Windows
        - windows
        - 0078D4
      - - Ubuntu
        - ubuntu
        - E95420
      - - Nvidia
        - nvidia
      - - Intel
        - intel
footer: ["Avatar Â©-Ask--"]
extra: ""
